# Generated by Django 2.2.10 on 2020-02-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('dept', models.CharField(choices=[('Finance', 'Finance'), ('Academics', 'Academics')], max_length=30)),
                ('emp_status', models.CharField(choices=[('terminated', 'terminated'), ('current', 'current')], max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=30)),
                ('profile_status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erpapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBank_Salary_Details',
            fields=[
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Professional_details', serialize=False, to='erpapp.Employee')),
                ('acc_name', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('acc_num', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBioData',
            fields=[
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erpapp.Employee')),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], max_length=30)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('others', 'others')], max_length=30)),
                ('physically_challenged', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC-CL', 'OBC Creamy Layer'), ('OBC-NCL', 'OBC Non Creamy Layer'), ('GEN-PWD', 'General Person with disabilties'), ('OBC-CL-PWD', 'OBC Creamy Layer Person with disabilites'), ('OBC-NCL-PWD', 'OBC Non Creamy Layer Person with disabilites'), ('SC-PWD', 'SC person with disabilites'), ('ST-PWD', 'ST person with disabilites')], max_length=25)),
                ('reservation', models.CharField(blank=True, choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC-NCL', 'OBC Non Creamy Layer'), ('PWD', 'General Person with disabilties'), ('SERVICE', 'Ex-Service Man'), ('GEN-ECO', 'General Category Economically Weaker Sections')], max_length=25, null=True)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeResearch_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=200)),
                ('Awards', models.TextField(max_length=200)),
                ('publishion_date', models.DateField(max_length=200)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_and_research_detail', to='erpapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfession_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('from_year', models.IntegerField()),
                ('to_year', models.IntegerField()),
                ('role', models.CharField(max_length=250)),
                ('pay_scale', models.IntegerField()),
                ('emoluments', models.IntegerField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_detail', to='erpapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAcademic_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('area_of_qualification', models.CharField(max_length=200)),
                ('category_of_university', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('ResultAwaited', 'ResultAwaited'), ('FinalAwaited', 'FinalAwaited'), ('Ongoing', 'Ongoing')], max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_detail', to='erpapp.Employee')),
            ],
        ),
    ]
